# Generated by Django 3.1.5 on 2021-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('iPhone', 'iPhone'), ('iMac', 'iMac'), ('Airpods', 'Airpods'), ('Mouse', 'Mouse')], max_length=50),
        ),
    ]
